lastTimeUsed=1728371741121
isReadOnly=false
sources=
packPathType=GALACTIC_ADVENTURES
packPath=
packageName=Ramone_Kemono's_2nd_MMD_Drag_Ball.package
embeddedEditorPackages=None
showOnlyModded=false
